[build]
  functions = "src"
  publish = "src"

[[redirects]]
  to="/.netlify/functions/api/:splat"
  from="/api/*"
  status=200

[[redirects]]
  from = "/photos/*"
  to = "/photos/:splat"
   status = 200  